### ISSUE TITLE
Feature request: allow users to specify class name on any element (without BEM)

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [KittyGiraudel/eleventy-plugin-footnotes#20]
Hi Kitty,

Thanks so much for this plugin! 

I think it would be nice if the plugin exposed an API for adding a custom class name (or multiple class names) to any one of the individual elements that it renders, like the `ol`, `li`, or anchors. That way, it's more flexible and less opinionated out of the box.

For example, in my use case, I have a custom utility class that applies some standard styling to all lists. I want to be able to apply this class to the `ol` itself, but it's not currently possible to do this because the plugin strictly enforces BEM.

Here's how `markdown-it-toc-done-right` does things, just as an example:

```js
.use(markdownItTocDoneRight, {
    listClass: 'list toc-list',
    itemClass: 'toc-item',
    linkClass: 'toc-link',
    listType: 'ol',
  })
```

The benefit of this is that you can still enforce BEM yourself while also including additional classes as needed.

**Comment by KittyGiraudel** [comment]
Thank you for getting back to me with some suggestions! Given the plugin already gives `baseClass` and uses BEM, I would say the first option is the best right now. Shall we try that?

**Comment by AleksandrHovhannisyan** [comment]
Sure! I'll put up a PR when I have some time. Thanks!
