### ISSUE TITLE
Deprecation of `doc-endnote` role

### ISSUE THREAD

**Issue by 7studio** [KittyGiraudel/eleventy-plugin-footnotes#22]
Hi Kitty,

First, thank you for this component (and generally for all your works) which helped us build our own into aem env.

I would like your point of view concerning the deprecation of the `doc-endnote` role: https://www.w3.org/TR/dpub-aria-1.1/#doc-endnote and the recently change into Axe https://github.com/dequelabs/axe-core/issues/2759

What is your recommandation about this change? Should we simply remove the role on `<li>` or change it for another one like `doc-footnote`?

Thank you for your time and your answer.

Xavier.

**Comment by KittyGiraudel** [comment]
Hello Xavier,

Thank you for reaching out and for the kind words. I wasn’t aware, so very nice of you to share this information! I guess as soon as Axe flags this as “not okay”, we should update the library’s markup to remove it. Until then, I guess it’s fine to keep it. :)

**Comment by AleksandrHovhannisyan** [comment]
@KittyGiraudel Sure! I can push up a PR.

**Comment by KittyGiraudel** [comment]
Done in v0.11.0. Thank you! :)
